---
title: "Research"
---

**Weber, Rosa** and Jan Saarela. 2023. *Who Migrates in a Context of Free Mobility? Assessing the Reason for Migration and Integration Patterns using Cross-national Register Data from Finland and Sweden.* European Journal of Population 39(17): 1–28. [Find the paper here](https://link.springer.com/article/10.1007/s10680-023-09667-2) \
\
**Weber, Rosa** and Douglas S. Massey. 2023. *Assessing the Effect of Increased Deportations on Mexican Migrants’ Remittances and Savings Brought Home.* Population Research and Policy Review 42(24): 1–27. [Find the paper here](https://link.springer.com/article/10.1007/s11113-023-09772-4) \
\
**Weber, Rosa** and Louisa Vogiazides. 2023. *Heterogeneity or consistency across life domains? An analysis of disparities between second-generation migrants and the Swedish majority population.*  Research in Social Stratification and Mobility 83(2023): 100744. [Find the paper here](https://www.sciencedirect.com/science/article/pii/S0276562422000713) \

**Weber, Rosa**. 2022. *Apprehension and Educational Outcomes among Hispanic Students in the United States: The Impact of Secure Communities.* PLOS ONE 17(1): e0276636. [Find the paper here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0276636) \
\
Fessler, Pirmin, Maria Silgoner and **Rosa Weber**. 2020. *Financial knowledge, attitude and behavior: Evidence from the Austrian Survey of Financial Literacy.* Empirica 47: 929–947. [Find the paper here](https://link.springer.com/article/10.1007/s10663-019-09465-2) \
\
**Weber, Rosa** and Jan Saarela. 2019. *Circular migration in a Context of Free Mobility: Evidence from Linked Population Register Data from Finland and Sweden.* Population Space and Place 25: e2230. [Find the paper here] (https://onlinelibrary.wiley.com/doi/full/10.1002/psp.2230)\
\
Saarela, Jan and **Rosa Weber**. 2017. *Assessment of educational misclassification in register-based data on Finnish immigrants in Sweden.* Scandinavian Journal of Public Health 45(17_suppl): 20–24. [Find the paper here](https://journals.sagepub.com/doi/10.1177/1457496917702322)\
\
**Weber, Rosa**. *Does intermarriage change migrants’ preferences for the home country?* IZA Journal of Migration 4(7): 1–21. [Find the paper here](https://izajodm.springeropen.com/articles/10.1186/s40176-015-0032-0) \

### Working papers

**Weber, Rosa** and Jan Saarela. *Cultural proximity and migration: Evidence from multigenerational population registers on mother tongue.* Stockholm Research Reports in Demography. Preprint. [Find the working paper here](https://su.figshare.com/articles/preprint/Cultural_proximity_and_migration_Evidence_from_multigenerational_population_registers_on_mother_tongue/24118659)
