---
title: "Teaching"
---

### Course coordinator
*Introduction to Statistical Reasoning and Quantitative Methods*. 01/2025 - present \
Master’s level. Governing the Large Metropolis master’s program, Sciences Po Paris (in English)\
\
*Demography*. 11/2024 - present\
Master’s level. ENSAE, École Polytechnique Paris (in English)\

### Lecturer and seminar leader
*Mesosociology: Organizations and Networks*. 11/2020 - 09/2021\
Bachelor level. Stockholm University (in Swedish)\
*Basic Sociology*. 01/2017 - 04/2020\
Bachelor level. Stockholm University (in Swedish)\
*Ethnicity and Integration*. 12/2018 - 05/2019\
Bachelor level. Stockholm University (in Swedish and English)\
*Quantitative Analysis*. 10/2016 - 04/2019\
Bachelor level. Stockholm University (in Swedish)\
*Introduction to Quantitative Data Management and Statistics*. 11/2016 - 01/2017\
Master’s level. Stockholm University (in English)\

### Supervision
*Supervision of Master’s theses*. 10/2022 - present\
at INED and Stockholm University (2 students, in French and English)\
\
*Supervision of Bachelor theses*. 02/2020 - present\
at Stockholm University (22 students, in Swedish)
